### ISSUE TITLE
Finish twitter cards

### ISSUE THREAD

**Issue by OstlerDev** [dloa/oip-seo#1]
Add the correct tags and test all of them. Card player does not work.

**Comment by copernicus-mogley** [comment]
Some changes to Twitter tags were made here: https://github.com/dloa/oip-seo/commit/b4843c250f43df30e0c9e386d98d6e49fa2d6b5c

The twitter:player tag still needs work and I'm working to resolve remaining issues today.

**Comment by copernicus-mogley** [comment]
I believe that all of the Twitter cards are setup correctly now. Waiting for *.alexandria.io to be whitelisted by Twitter before this can be verified and used.

**Comment by copernicus-mogley** [comment]
- [x] Summary cards (Documents + Things + Publishers)
- [x] Audio https://github.com/dloa/oip-seo/issues/3
